### ISSUE TITLE
Strange result in Hamburg forecast probable matchups

### ISSUE THREAD

**Issue by NicolasP** [mcekovic/tennis-crystal-ball#277]
In the [probable matchups tab of Hamburg forecasts](http://www.ultimatetennisstatistics.com/inProgressEventForecast?inProgressEventId=104#probable), Leonardo Mayer has only a 39.8% chance of defeating Marco Cecchinato in R16, but it's still him who appears in QF against Diego Schwartzman. This seems like a bug.

![screenshot_2018-07-24 ultimate tennis statistics - hamburg forecast](https://user-images.githubusercontent.com/1526/43129886-a454d1e0-8f35-11e8-9f1c-aab75a7c9bd3.png)

By the way, we can also see that Pablo Carreño Busta is moved to SF despite being slightly less favored to win than Kohlshcreiber.

**Comment by mcekovic** [comment]
Thanks for noticing. This is known issue in the presentation, but it is actually indented so.
The reason for Leonardo Mayer to be chosen to go to QF is because overall his probability to go to QF (from R32) is greater then Marco Ceccinato, as Leonardo Mayer can have either enough easier opponent in R32 then Marco Ceccinato (to annulate probability advantage Marco would have over Leonardo in R16), or, as in this particular case, as Leonardo has already won his R32 match and Marco is still to play it.
Thus overall probability to reach QF is currently greater for Leonardo (40.0%) then for Marco (31.1%), as can be seen in the 'Current' tab.
If Marco wins his R32 match, he would be chosen as favorite to reach QF (in a R16 match versus Leonardo).
Hope this explanation makes sense, as it is not obvious.

There is a hint text in 'Probable Matchups' that tries to hint this:

 + Probable matches are determined by player pairs that are most probable to meet in the some round based on the draw, current tournament results and predictions for future results
++ Probabilities and odds in the probable matchup box represent probabilities for one player to win over the other, but only if the matchup really happens

**Comment by NicolasP** [comment]
OK, thanks for the explanation! It is indeed slightly confusing in the way it's presented but now it makes sense.

**Comment by mcekovic** [comment]
TODO: Investigate if this can be better hinted in GUI.
