### ISSUE TITLE
Missing all match data for Ugo Humbert (rank 139)

### ISSUE THREAD

**Issue by darkFunction** [mcekovic/tennis-crystal-ball#288]
http://www.ultimatetennisstatistics.com/matchesTable?playerId=44831&current=1

Thank you for this amazing site, btw. Congrats on a huge piece of work

**Comment by mcekovic** [comment]
Turns out that Ugo Humbert had played his first ATP matches at USO 2018. The website updates Monday early morning, but this Mondays, ATP has some problems on the website, so automatic updates on UTS for USO 2018 did not work and I had to initiate the update manually, so it was late couple of hours.
Please note hat Qualifying, Challengers and Futures matches are not yet available on UTS.

**Comment by darkFunction** [comment]
Thank you!
