### ISSUE TITLE
Load new tournament problems.

### ISSUE THREAD

**Issue by jhzao82** [mcekovic/tennis-crystal-ball#297]
It looks like players will not display when delete two complete tournament events and run load-data -ln again.

Date | Tournament | Surface | Draw | Final
-- | -- | -- | -- | --
22-10-2018 | Basel | Hard (i) | KO 32 | Roger Federer (1) d. Marius Copil (Q) 7-6(5) 6-4
22-10-2018 | Vienna | Hard (i) | KO 32 | Kevin Anderson (2) d. Kei Nishikori (5) 6-3 7-6(3)
15-10-2018 | Antwerp | Hard (i) | KO 28 |  
15-10-2018 | Moscow | Hard (i) | KO 28 | Karen Khachanov d. Adrian Mannarino (3) 6-2 6-2
15-10-2018 | Stockholm | Hard (i) | KO 28 |  

also, another new tournament is load faild. 

PL/pgSQL function load_in_progress_match(text,smallint,smallint,smallint,date,text,boolean,text,smallint,text,text,smallint,text,text,text,smallint,text,smallint,text,text,smallint,smallint,smallint,smallint,smallint,smallint,smallint[],smallint[],smallint[],smallint[],smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint,smallint) line 79 at SQL statement  Call getNextException to see other errors in the batch.
Error loading and forecasting in-progress tournament: paris/352
java.sql.BatchUpdateException: Batch entry 0 select * from load_in_progress_match('352', 1, NULL, NULL, '2018-10-29 +08'::date, 'H', 'TRUE', 'R64', 3, 'Rafael Nadal', NULL, 1, NULL, NULL, NULL, NULL, NULL, 1, 'W/O', 'W/O', 0, 0, 0, 0, 0, 0, '{}', '{}', '{}', '{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) as result was aborted: ERROR: null value in column "in_progress_match_id" violates not-null constraint

**Comment by mcekovic** [comment]
Well, as explained in previous issue, the final matches lack for the two events at ATP web site.
Regarding the other issue, should be ok if you pull the latest updates.

**Comment by mcekovic** [comment]
Generally, I do not guarantee UTS full data load will work all the season and I will not maintain to work as data in Jeff Sackmann repo change and ATP web site changes over time.
However, usually, at the end of the season there will be a full data rebuild in UTS production DB, so in October and November I fix the accumulated data and data load issues, so that at the time production DB is rebuilt in the tennis off season, data load and data is as good as possible.
During the season, only incremental data updates will probably work.
But given the unpredictability of new data and ATP web site changes, even I have to manually fix or correct something once in while to keep the production updated...
So I will try to help, but that would not be possible all the time.

**Comment by jhzao82** [comment]
It's a little can not see! I rebuild the database now, the in Progress Events Forecasts come out!

But I still can not see players, I will go back later!

Thank you!
